# Use the official Nginx image as a base
FROM nginx:latest
RUN apt update
RUN apt install net-tools
RUN apt install telnet -y
RUN apt install iputils-ping -y
RUN apt install tcpdump -y

# Copy the custom configuration file to the appropriate location
COPY nginx.conf /etc/nginx/nginx.conf
